"use client";
import { useMemo, useState } from "react";
type Option = { id: string; label: string };
const uses: Option[] = [{id:"support",label:"Customer support"},{id:"knowledge",label:"Knowledge assistant"},{id:"content",label:"Content workflow"},{id:"coding",label:"Software engineering"},{id:"automation",label:"Business automation"},{id:"research",label:"Research & analysis"}];
export default function AIStackBuilder() {
  const [useCase,setUseCase]=useState("support"); const [data,setData]=useState("company"); const [actions,setActions]=useState("review"); const [scale,setScale]=useState("small");
  const stack=useMemo(()=>{
    const privateData=data!=="public"; const needsRetrieval=privateData||["knowledge","support","research"].includes(useCase); const needsTools=["support","coding","automation"].includes(useCase); const model=useCase==="coding"?"Code-capable reasoning model":useCase==="content"?"General multimodal model":"General reasoning model";
    return [
      {k:"Model layer",v:model,d:"Benchmark at least two suitable models on representative tasks; route simpler work to cheaper models where quality holds."},
      {k:"Knowledge layer",v:needsRetrieval?"Retrieval + controlled knowledge base":"Prompt/context layer first",d:needsRetrieval?"Index approved sources, retrieve relevant context and preserve source traceability.":"Avoid adding a vector database until the workflow actually needs persistent private knowledge."},
      {k:"Action layer",v:needsTools?"Tool/API orchestration":"No autonomous tools required initially",d:needsTools?"Expose only the minimum tools needed and validate arguments before external actions.":"Keep the first version read-only and measure quality before adding actions."},
      {k:"Safety layer",v:actions==="auto"?"Policy gates + audit logs":"Human approval checkpoint",d:actions==="auto"?"Autonomous actions need strict scopes, authentication, limits, logging and recovery paths.":"Require a person to approve consequential outputs or actions before execution."},
      {k:"Infrastructure",v:scale==="large"?"Queue + observability + scalable API runtime":"Simple managed app runtime",d:scale==="large"?"Design for retries, rate limits, concurrency, tracing, cost monitoring and graceful degradation.":"Start simple; add queues and distributed components only when traffic or latency justifies them."}
    ];
  },[useCase,data,actions,scale]);
  return <div className="finder-shell"><div className="finder-controls"><div><span className="finder-label">1 · Primary workflow</span><div className="choice-grid">{uses.map(x=><button key={x.id} className={useCase===x.id?"choice active":"choice"} onClick={()=>setUseCase(x.id)}>{x.label}</button>)}</div></div><label>2 · What data will it use?<select value={data} onChange={e=>setData(e.target.value)}><option value="public">Mostly public/general knowledge</option><option value="company">Private company documents/data</option><option value="sensitive">Sensitive or regulated data</option></select></label><label>3 · How should actions work?<select value={actions} onChange={e=>setActions(e.target.value)}><option value="read">Read/generate only</option><option value="review">Act after human approval</option><option value="auto">Autonomous actions</option></select></label><label>4 · Expected scale<select value={scale} onChange={e=>setScale(e.target.value)}><option value="small">Prototype / small team</option><option value="medium">Production / growing usage</option><option value="large">High-volume production</option></select></label></div><div className="finder-results" aria-live="polite"><div className="eyebrow">Suggested architecture</div><h2>Build the minimum reliable stack.</h2><p className="meta">This is an architecture starting point—not a vendor endorsement. Validate security, compliance, model quality and economics for your environment.</p>{stack.map((x,i)=><article className="finder-result" key={x.k}><span>{String(i+1).padStart(2,"0")}</span><div><small>{x.k}</small><h3>{x.v}</h3><p>{x.d}</p></div></article>)}</div></div>;
}
