import {StepByStepGuide} from "@/components/StepByStepGuide";

export function AIPrivacyGuide(){return <StepByStepGuide
 outcome="Decide whether an AI workflow is appropriate for sensitive information by mapping the data path, checking current provider controls, minimizing access, testing deletion and defining safer alternatives before real sensitive data is used."
 prerequisites={["The exact AI product, plan and integrations you intend to use.","A description of the data you want to process and why it is needed.","Access to the provider’s current privacy, security, retention and product documentation.","For organizational use, the relevant security, privacy, legal or procurement owner when required by policy."]}
 steps={[
  {title:"Classify the data before uploading anything",body:<><p>Identify whether the workflow involves public, internal, confidential, personal, regulated, credential, financial, health, customer, employee, source-code or other sensitive information. Follow your organization’s classification rules where they exist.</p></>,expected:<p>You know the highest sensitivity level present in the intended input.</p>},
  {title:"Map the complete data path",body:<><p>List the application, model provider, storage, logs, connected apps, plugins, retrieval systems, analytics and other processors involved. Include generated outputs because they can reproduce sensitive source information.</p></>,expected:<p>You can draw where information enters, travels, is stored and leaves the workflow.</p>},
  {title:"Verify the exact product and plan",body:<><p>Do not assume consumer, business, enterprise and API offerings use identical controls. Check the current documentation for the exact service you will use, including retention, training/model-improvement settings and administrative options.</p></>,expected:<p>Your privacy decision is based on the actual offering rather than the provider’s brand in general.</p>},
  {title:"Check retention and deletion",body:<><p>Determine how long prompts, files, outputs, logs and backups may remain, what controls administrators or users have, and what deletion does and does not cover. Record the source and date of the policy you reviewed.</p></>,expected:<p>You understand the retention lifecycle well enough to compare it with your requirements.</p>},
  {title:"Check model-improvement and training controls",body:<><p>Verify whether submitted content may be used to improve models or services and whether the relevant plan offers controls. Do not rely on remembered settings because product policies can change.</p></>,expected:<p>You know whether your intended data use is compatible with the current service terms and settings.</p>},
  {title:"Minimize the data",body:<><p>Remove names, identifiers, credentials, secrets, unrelated document sections and other information the task does not require. Prefer redacted, synthetic or representative data during setup and testing.</p></>,expected:<p>The AI receives only the minimum information needed to perform the task.</p>},
  {title:"Reduce permissions",body:<><p>Connect only the repositories, folders, mailboxes, databases and actions required. Prefer read-only access while testing. Keep production credentials and broad administrative permissions away from AI agents unless a reviewed design explicitly requires them.</p></>,expected:<p>A mistake or compromised integration has a limited blast radius.</p>},
  {title:"Review every integration",body:<><p>Check browser extensions, plugins, automation services, retrieval layers and connected applications separately. A strong primary provider policy does not automatically cover data sent to another service.</p></>,expected:<p>There is no unreviewed third party hidden in the workflow.</p>},
  {title:"Test with non-sensitive data first",body:<><p>Use synthetic or low-risk examples to verify uploads, outputs, logs, sharing behavior, access permissions and deletion controls. Confirm that the workflow behaves as expected before introducing real sensitive material.</p></>,expected:<p>You have observed the actual workflow without exposing important data during setup.</p>},
  {title:"Choose a safer architecture when requirements do not fit",body:<><p>If the service cannot satisfy your requirements, consider a different plan/provider, a controlled API design, local processing, redaction, retrieval that exposes smaller passages, or keeping the task out of AI entirely.</p></>,expected:<p>The architecture follows the data requirement rather than forcing sensitive data into a convenient tool.</p>},
  {title:"Document approval and re-check dates",body:<><p>Record what was approved, by whom where appropriate, the reviewed policy sources, configuration, connected systems and the date for re-review. Re-check after material provider, plan, integration or policy changes.</p></>,expected:<p>The privacy decision is auditable and can be revisited when the system changes.</p>}
 ]}
 verification={["The data has been classified and minimized.","Every provider and integration in the data path is known.","Retention, deletion and model-improvement controls were checked for the exact product/plan.","Permissions follow least-privilege principles.","The workflow was tested with non-sensitive data first.","Required organizational review or approval is complete before sensitive production use."]}
 troubleshooting={[
  {problem:"The provider documentation is unclear",fix:"Do not fill gaps with assumptions. Ask the provider or your organization’s responsible owner, reduce the sensitivity of the data, or choose a workflow whose controls can be verified."},
  {problem:"The tool needs access to an entire drive or mailbox",fix:"Look for narrower scopes, a dedicated folder/account, retrieval middleware, or another product. Broad access should be justified by the task, not accepted merely because setup is easier."},
  {problem:"Users paste sensitive data despite policy",fix:"Combine training with technical controls: data-loss prevention where available, permission limits, safer approved tools, clear UI warnings and monitoring appropriate to your organization."},
  {problem:"A local model is assumed to solve every privacy issue",fix:"Review the full local stack. Extensions, telemetry, remote APIs, backups, network exposure and insecure devices can still move or expose data."},
  {problem:"The service terms changed",fix:"Pause affected sensitive workflows if necessary, compare the new terms with the documented requirement, update controls and obtain any required re-approval before continuing."}
 ]}
><section><h2>Important boundary</h2><p>This checklist is a practical risk-review framework, not legal advice or a substitute for your organization’s security, privacy, regulatory or contractual requirements. Higher-risk data may require specialist review before any AI processing.</p></section></StepByStepGuide>}
