import {StepByStepGuide} from "@/components/StepByStepGuide";

export function AIWorkflowAutomationGuide(){return <StepByStepGuide
 outcome="Design and pilot an AI-assisted workflow that uses models only where flexible language or judgment helps, keeps deterministic rules in ordinary software, and has clear validation, approvals, fallbacks and measurements before autonomy is increased."
 prerequisites={["One repetitive workflow with a clear beginning and end.","Examples of real inputs and the correct or acceptable outcomes.","The business rules, permissions and systems involved in the process.","A human owner who can review failures during the pilot."]}
 steps={[
  {title:"Map the current workflow",body:<><p>Write each step from trigger to completion, including systems touched, decisions made, manual handoffs, waiting time and common failure points. Measure the current baseline before adding AI.</p></>,expected:<p>You have a visible process map and baseline for time, volume, errors or manual effort.</p>},
  {title:"Separate deterministic work from judgment",body:<><p>Mark exact calculations, database constraints, permissions, known routing rules and required validations as deterministic. Mark messy language, classification, extraction, summarization or drafting as potential AI tasks.</p></>,expected:<p>You are not using a probabilistic model for rules that ordinary code can enforce exactly.</p>},
  {title:"Choose one narrow AI-assisted step",body:<><p>Start with a bounded task such as classifying an incoming request, extracting fields from a document, drafting a response, or recommending a route. Avoid automating the entire process in the first iteration.</p></>,expected:<p>The first AI component has a clear input, output and definition of success.</p>},
  {title:"Define a structured contract",body:<><p>Specify the fields the model should return, allowed labels, required evidence and how missing information is represented. Validate structured output in code before downstream systems use it.</p></>,expected:<p>Malformed or incomplete model output can be detected automatically.</p>},
  {title:"Add deterministic validation",body:<><p>Check types, required fields, allowed values, business rules, permissions and database constraints outside the model. Reject or route invalid output rather than asking downstream systems to trust it.</p></>,expected:<p>The workflow has software-enforced boundaries around probabilistic output.</p>},
  {title:"Design the human approval point",body:<><p>For meaningful consequences, show the reviewer the proposed action, important source evidence and what will happen after approval. Make rejection and correction easy so humans do not become a rubber stamp.</p></>,expected:<p>Consequential actions cannot silently execute merely because the model sounded confident.</p>},
  {title:"Design for failure before success",body:<><p>Define what happens on timeout, malformed output, unavailable APIs, missing documents, ambiguous inputs and duplicate events. Use bounded retries, fallbacks, escalation and idempotency where actions could otherwise be repeated.</p></>,expected:<p>A predictable failure path exists for the common ways the system can break.</p>},
  {title:"Test with a representative benchmark",body:<><p>Run normal, difficult and known-failure examples. Measure extraction/classification quality, workflow completion, human corrections, latency and cost. Keep the benchmark for regression testing.</p></>,expected:<p>The system is evaluated on real process outcomes rather than an impressive demonstration.</p>},
  {title:"Pilot with limited scope",body:<><p>Start with a small team, queue, dataset or recommendation-only mode. Preserve audit information needed to understand failures without collecting unnecessary personal data.</p></>,expected:<p>Production-like behavior can be observed while the blast radius remains limited.</p>},
  {title:"Measure end-to-end value",body:<><p>Compare the pilot with the original baseline: completion rate, handling time, manual intervention, severe errors, latency and total operating cost. Include review and correction time.</p></>,expected:<p>You know whether the automation actually improves the process rather than merely moving work elsewhere.</p>},
  {title:"Increase autonomy only when evidence supports it",body:<><p>Remove human review only for well-understood, low-risk actions whose measured reliability and controls justify it. Keep approval for higher-impact or ambiguous cases and continue monitoring regressions.</p></>,expected:<p>Autonomy grows from evidence and controls instead of enthusiasm for agentic features.</p>}
 ]}
 verification={["The original process and baseline are documented.","AI is used only for steps where probabilistic capability adds value.","Model outputs are validated by deterministic software.","Consequential actions have appropriate permission and approval controls.","Timeouts, malformed outputs, duplicate actions and escalation paths are handled.","The pilot is measured against end-to-end business outcomes.","A regression benchmark exists before the workflow is expanded."]}
 troubleshooting={[
  {problem:"The automation saves no time",fix:"Measure where effort moved. Human review, exception handling, slow APIs or poor extraction may consume the apparent savings. Narrow or redesign the AI step based on the bottleneck."},
  {problem:"The model returns inconsistent fields",fix:"Use a strict structured schema, validate it in code, provide representative examples, and reject invalid responses. Do not let malformed model output flow directly into business systems."},
  {problem:"Retries create duplicate actions",fix:"Add idempotency keys or state checks around consequential operations. Retrying model generation and retrying an external action should be treated as different concerns."},
  {problem:"Reviewers approve everything without checking",fix:"Reduce unnecessary approvals and make important evidence, proposed changes and consequences visible. Human review is useful only when the reviewer can realistically detect a problem."},
  {problem:"The workflow fails on unusual inputs",fix:"Add those cases to the regression set, define an uncertainty or escalation path, and avoid forcing the model to produce a normal answer when required information is missing."}
 ]}
><section><h2>A practical architecture pattern</h2><p>A robust pattern is <strong>Trigger → deterministic preprocessing → AI classification/extraction/draft → schema validation → business-rule checks → human approval when required → action → audit/measurement</strong>. Not every workflow needs every stage, but keeping model judgment separate from permissions and exact rules makes failures easier to control.</p></section></StepByStepGuide>}
