import {StepByStepGuide} from "@/components/StepByStepGuide";

export function EvaluateAIOutputGuide(){return <StepByStepGuide
 outcome="Build a repeatable evaluation process that tells you whether AI output is accurate, complete, supported, safe enough for its intended use, and genuinely useful in the workflow."
 prerequisites={["A clearly defined AI task or workflow.","Representative inputs from the kind of work the system will actually receive.","Authoritative references, expected outputs, tests, or knowledgeable reviewers where correctness can be checked.","A place to record results so different models, prompts or versions can be compared consistently."]}
 steps={[
  {title:"Define the decision the evaluation must support",body:<><p>State what you are deciding: whether an output can be published, whether a model is suitable for a workflow, whether a prompt revision improved quality, or whether automation can safely proceed without human review.</p></>,expected:<p>The evaluation has a concrete pass/fail or comparison purpose.</p>},
  {title:"Turn quality into measurable criteria",body:<><p>Separate dimensions such as factual accuracy, completeness, instruction following, citation support, format, consistency, safety, latency and cost. Weight criteria according to the consequences of failure.</p></>,expected:<p>Reviewers know what “good” means before seeing the model output.</p>},
  {title:"Build a representative test set",body:<><p>Include normal tasks, difficult cases, ambiguous inputs, incomplete information and known failure modes. Keep a stable core set for regression testing and add new production failures over time.</p></>,expected:<p>Your test set resembles the real workload rather than a collection of easy demos.</p>},
  {title:"Create trusted references where possible",body:<><p>For factual questions, identify authoritative sources. For extraction, create labeled expected values. For code, define tests and expected behavior. For writing, define a rubric and examples rather than pretending there is one perfect answer.</p></>,expected:<p>Important dimensions can be judged against evidence rather than reviewer intuition alone.</p>},
  {title:"Run tests under controlled conditions",body:<><p>Keep prompts, settings, tools and inputs consistent when comparing systems. Record the model or product, date and relevant configuration because AI systems can change over time.</p></>,expected:<p>Differences in results are less likely to be caused by accidental changes in the test setup.</p>},
  {title:"Verify claims and citations",body:<><p>Check factual statements against the authoritative references. Open cited sources and confirm that they actually support the claim being made. Treat fabricated or mismatched citations as substantive failures.</p></>,expected:<p>Supported claims are distinguished from plausible-sounding unsupported text.</p>},
  {title:"Test executable output",body:<><p>Run code tests, validate structured data against its schema, calculate numerical results independently, and inspect proposed changes before applying them. Prefer objective execution where the artifact allows it.</p></>,expected:<p>Outputs that can be mechanically verified have been tested rather than merely read.</p>},
  {title:"Repeat variable tasks",body:<><p>Run important examples multiple times when the system is non-deterministic. Record success frequency and severity of failures. One impressive response is not evidence of reliable performance.</p></>,expected:<p>You have a reliability picture, not a best-case screenshot.</p>},
  {title:"Review high-impact failures separately",body:<><p>A harmless style issue and a fabricated legal, financial, medical, security or production instruction should not contribute equally to one average score. Track severe failures and define escalation or human-review requirements.</p></>,expected:<p>Critical errors cannot be hidden by good performance on low-risk criteria.</p>},
  {title:"Compare the complete workflow",body:<><p>Measure review time, manual corrections, latency, tool failures and cost alongside output quality. The best model score may not produce the best operational workflow.</p></>,expected:<p>You can choose based on end-to-end value and risk rather than model reputation.</p>},
  {title:"Create a regression loop",body:<><p>After launch, collect appropriate failure examples without retaining unnecessary personal data. Add important cases to the benchmark and rerun it when prompts, models, retrieval, tools or policies change.</p></>,expected:<p>Evaluation continues as the system and real-world inputs evolve.</p>}
 ]}
 verification={["The rubric was defined before judging candidate outputs.","The test set includes normal, difficult and known-failure cases.","Factual claims, citations, code or structured outputs are independently checked where possible.","Severe failures are tracked separately from cosmetic issues.","Results include workflow cost and review effort, not only output quality.","A stable regression set can be rerun after future changes."]}
 troubleshooting={[
  {problem:"Reviewers disagree constantly",fix:"Make rubric criteria more concrete, add examples of pass/fail behavior, calibrate reviewers on the same sample, and record unresolved disagreement rather than averaging it away."},
  {problem:"Everything scores highly but production users still complain",fix:"Your test set is probably not representative enough. Add real failure modes, edge cases and end-to-end workflow constraints rather than only clean benchmark prompts."},
  {problem:"The overall score hides serious mistakes",fix:"Separate critical failure rates and minimum thresholds from average quality scores. Some dimensions should be gates, not points that can be offset by better style."},
  {problem:"A new model seems better but the comparison feels unfair",fix:"Freeze representative inputs, prompts, tool access and scoring rules before comparing. Record configuration and test date for each candidate."},
  {problem:"Evaluation is becoming too expensive",fix:"Keep a smaller stable regression suite for frequent checks and a larger comprehensive suite for major releases. Automate objective checks such as schemas, tests and exact-match fields where appropriate."}
 ]}
><section><h2>What not to do</h2><p>Do not ask the same model to grade itself and treat that judgment as independent proof. Model-based graders can be useful as one signal at scale, but important evaluations should be calibrated against trusted references or human judgment and checked for grader bias.</p></section></StepByStepGuide>}
