import {StepByStepGuide} from "@/components/StepByStepGuide";

export function OllamaWindowsGuide(){return <StepByStepGuide
  outcome="Install Ollama on a supported Windows PC, download and run a local model, verify the local API, understand where models are stored, and know how to diagnose the most common setup problems."
  prerequisites={[
    "Windows 10 22H2 or newer (Home or Pro).",
    "At least 4 GB of free space for the Ollama installation plus substantially more storage for model files.",
    "A current supported GPU driver if you intend to use NVIDIA or AMD acceleration; CPU/system-memory execution can be slower.",
    "PowerShell, Command Prompt, or Windows Terminal.",
    "Enough RAM/VRAM for the model you choose. Start small if you are unsure."
  ]}
  steps={[
    {title:"Check Windows and available hardware",body:<><p>Open <strong>Settings → System → About</strong> and confirm your Windows version. Open Task Manager → Performance to note installed memory and, if present, dedicated GPU memory. Also check free disk space before downloading a model.</p><p>Do not begin with the largest model your PC can theoretically load. A smaller model that responds reliably is a better first test.</p></>,expected:<p>You know your Windows version, RAM, GPU/VRAM if available, and free storage.</p>},
    {title:"Download Ollama from the official installer",body:<><p>Use the official Ollama Windows download and run <code>OllamaSetup.exe</code>. The standard installer installs for your user account and does not normally require Administrator rights.</p><p>If you intentionally need another install directory, Ollama documents the installer option <code>OllamaSetup.exe /DIR=&quot;d:\some\location&quot;</code>.</p></>,expected:<p>Ollama appears as an installed Windows application and can run in the background.</p>},
    {title:"Verify the command-line installation",body:<><p>Open a <em>new</em> PowerShell or Command Prompt window and run:</p><pre><code>ollama</code></pre><p>If Windows cannot find the command, close and reopen the terminal first so the updated PATH is loaded.</p></>,expected:<p>The Ollama command responds instead of showing “command not found” or “not recognized”.</p>},
    {title:"Choose a sensible first local model",body:<><p>Use a model that fits comfortably in your available memory. If you do not know what size is appropriate, use the TechPulse Local LLM Hardware Checker before downloading large files.</p><p>Model sizes, quantization and context length all affect memory use, so leave headroom for Windows and other applications.</p></>,expected:<p>You have selected a model that is realistic for your hardware rather than simply the largest available model.</p>},
    {title:"Download and run the model",body:<><p>From the terminal, run the model name you selected. Ollama’s current quickstart, for example, uses:</p><pre><code>ollama run gemma4:e2b</code></pre><p>On first use, Ollama downloads the model and then opens an interactive chat. Enter a simple test prompt. Type <code>/bye</code> when you want to leave the chat.</p></>,expected:<p>The model downloads successfully and generates a coherent response locally.</p>},
    {title:"Test a real task and watch resource usage",body:<><p>Run a prompt similar to the work you actually intend to do: summarization, coding, drafting, or analysis. While it generates, open Task Manager → Performance and observe memory, CPU and GPU utilization.</p><p>If Windows becomes unresponsive, the model is extremely slow, or memory is exhausted, move to a smaller model or lower-memory variant.</p></>,expected:<p>You know whether the chosen model is usable—not merely loadable—on your PC.</p>},
    {title:"Verify the local Ollama API",body:<><p>Ollama serves its local API at <code>http://localhost:11434</code>. In PowerShell you can test generation with a POST request. Replace the model name with the one you downloaded:</p><pre><code>{`(Invoke-WebRequest -Method POST -Body '{"model":"gemma4:e2b","prompt":"Reply with: API working","stream":false}' -ContentType 'application/json' -Uri http://localhost:11434/api/generate).Content`}</code></pre><p>Local model requests do not require an Ollama cloud API key.</p></>,expected:<p>PowerShell returns JSON containing a generated response from your local model.</p>},
    {title:"Change model storage location if needed",body:<><p>Model files can consume tens or hundreds of gigabytes. To move future model storage, open Windows environment-variable settings and create the user variable <code>OLLAMA_MODELS</code> with the destination folder.</p><p>Quit the Ollama tray application and relaunch it after changing the variable. A new terminal should also be opened after environment-variable changes.</p></>,expected:<p>Ollama uses the storage location you deliberately configured rather than unexpectedly filling the system drive.</p>},
    {title:"Record your working configuration",body:<><p>Record the model name, model size/variant, Ollama version, available RAM/VRAM and whether performance is acceptable for your real task. This becomes your baseline before testing larger models or connecting an IDE or desktop application.</p></>,expected:<p>You have a repeatable local-AI setup and a baseline against which future upgrades can be compared.</p>}
  ]}
  verification={[
    "The ollama command opens successfully in a fresh terminal.",
    "Your selected model downloads and answers a test prompt.",
    "The model remains usable during a representative real-world task without exhausting system resources.",
    "A request to the local API on localhost:11434 returns a model response.",
    "You know where your models are stored and have enough disk space for future downloads."
  ]}
  troubleshooting={[
    {problem:"'ollama' is not recognized",fix:"Close the current terminal and open a new one. The Windows installer adds Ollama to your user PATH. If it still fails, confirm Ollama is installed under your user account and relaunch the application."},
    {problem:"The model downloads but runs extremely slowly",fix:"Try a smaller or more aggressively quantized model and close memory-heavy applications. A model that spills heavily into system RAM can be much slower than one that fits comfortably in available accelerated memory."},
    {problem:"The local API does not respond",fix:"Confirm the Ollama application is running. The normal local endpoint is http://localhost:11434. Restart Ollama and retry before changing firewall or network settings."},
    {problem:"The system drive is filling up",fix:"Models can be very large. Configure the OLLAMA_MODELS user environment variable to a drive with adequate capacity, then quit and relaunch Ollama."},
    {problem:"You need diagnostic logs",fix:"On Windows, Ollama documents logs under %LOCALAPPDATA%\\Ollama, including app.log and server.log. Inspect the newest relevant log after reproducing the failure."}
  ]}
><section><h2>Security and privacy notes</h2><p>Running the model locally keeps local inference on your computer, but that does not make every surrounding workflow private. IDE extensions, browser tools, plugins, telemetry, cloud fallbacks and network exposure can still transmit data. Review the complete data path before processing sensitive information.</p><p>Do not expose the local Ollama service to untrusted networks merely to make another device connect. Add authentication, network controls or a properly secured application layer if remote access becomes necessary.</p></section><section><h2>Where Ollama stores files on Windows</h2><p>Ollama documents application logs under <code>%LOCALAPPDATA%\Ollama</code>, binaries under <code>%LOCALAPPDATA%\Programs\Ollama</code>, and models/configuration under <code>%HOMEPATH%\.ollama</code> by default. The <code>OLLAMA_MODELS</code> environment variable can change model storage.</p></section><section><h2>Next steps</h2><p>Once the local setup is stable, the useful next move is to connect it to a real workflow—such as a coding agent, desktop application, retrieval system, or your own application through Ollama’s local API. Change one variable at a time when testing larger models so you can tell whether an upgrade actually improves quality enough to justify the extra memory and latency.</p></section></StepByStepGuide>}
