import {StepByStepGuide} from "@/components/StepByStepGuide";

export function PromptingGuide(){return <StepByStepGuide
 outcome="Turn a vague AI request into a repeatable prompt workflow that produces clearer, more useful output and gives you a reliable way to review and improve the result."
 prerequisites={["A real task you want an AI assistant to complete.","The source material or context the task actually requires.","A clear idea of the intended audience and final output format.","A way to verify important factual, numerical, technical, or policy claims before using the output."]}
 steps={[
  {title:"Write the outcome before the prompt",body:<><p>Describe what success looks like in one sentence. Name the deliverable, audience and purpose. For example: “Create a concise onboarding checklist for a new support agent who has never used our ticketing workflow.”</p><p>Avoid beginning with decorative roles such as “act as the world’s greatest expert.” The task definition carries more useful information.</p></>,expected:<p>You can explain the required result without referring to a particular AI model.</p>},
  {title:"Add only the context the model needs",body:<><p>Supply definitions, source text, constraints, background and terminology that materially affect the answer. Separate source material from instructions so the model can distinguish what it should use from what it should do.</p><p>Do not assume the assistant knows private company rules, a document you have not supplied, or a decision made elsewhere.</p></>,expected:<p>The request contains enough information to complete the task without inventing missing business context.</p>},
  {title:"State constraints explicitly",body:<><p>Specify important boundaries: length, tone, required sections, prohibited claims, data that must not be exposed, technologies that must be used, or information that must come only from supplied sources.</p><p>Keep constraints testable. “Be excellent” is subjective; “use no more than five bullets and cite every numerical claim” can be checked.</p></>,expected:<p>You have a short set of rules that can be evaluated after generation.</p>},
  {title:"Define the output format",body:<><p>Tell the model what the finished artifact should look like: table, JSON, email, checklist, code patch, numbered procedure, comparison matrix, or prose. If software will consume the result, specify the schema and validate it in software rather than trusting formatting instructions alone.</p></>,expected:<p>The first response is shaped for the workflow instead of requiring avoidable reformatting.</p>},
  {title:"Use examples when pattern matters",body:<><p>Provide one or two representative examples when tone, labeling, classification, or structure is difficult to describe precisely. Show the input and the desired output rather than supplying many redundant examples.</p></>,expected:<p>The model has a concrete pattern to imitate where verbal instructions were ambiguous.</p>},
  {title:"Tell the model how to handle uncertainty",body:<><p>For accuracy-sensitive work, explicitly allow the assistant to identify missing information, distinguish assumptions from known facts, and avoid manufacturing citations or details. Ask it to flag claims that require external verification.</p></>,expected:<p>Missing evidence is surfaced instead of silently converted into confident-looking content.</p>},
  {title:"Generate a first draft",body:<><p>Run the prompt without repeatedly adding instructions mid-generation. Preserve the prompt and output so you can identify which change actually improves the result during later iterations.</p></>,expected:<p>You have a baseline output produced from a reproducible prompt.</p>},
  {title:"Evaluate against a rubric",body:<><p>Check the result against the original outcome and constraints. Score the dimensions that matter: factual accuracy, completeness, instruction following, usefulness, tone, format, and unnecessary content.</p><p>Verify consequential claims against authoritative evidence rather than asking the same model whether its own answer is correct.</p></>,expected:<p>You know specifically why the output passes or fails instead of relying on a vague impression.</p>},
  {title:"Revise one failure at a time",body:<><p>If the output fails, identify the cause: missing context, ambiguous instruction, weak example, conflicting constraints, insufficient model capability, or a task that should use a tool rather than generation. Change the smallest relevant part and rerun the benchmark.</p></>,expected:<p>Prompt revisions are evidence-driven and you can tell which changes helped.</p>},
  {title:"Save the complete workflow, not just the words",body:<><p>Record the prompt, required inputs, model/tool used, evaluation criteria and any post-generation verification. Re-test important prompts as models and applications change.</p></>,expected:<p>You have a reusable workflow rather than a fragile “magic prompt.”</p>}
 ]}
 verification={["A new user can understand the task, context, constraints and expected output from the prompt alone.","The response can be checked against explicit acceptance criteria.","Important claims are verified independently where necessary.","The prompt works on more than one representative example.","Sensitive permissions and consequential actions are enforced by software or policy—not prompt wording alone."]}
 troubleshooting={[
  {problem:"The answer is generic",fix:"Add the missing audience, purpose, source material, constraints and a concrete definition of success. Generic inputs commonly produce generic outputs."},
  {problem:"The model ignores a requirement",fix:"Remove conflicting instructions, make the requirement measurable, place important constraints clearly, and reduce unrelated context."},
  {problem:"The output format keeps changing",fix:"Provide an explicit structure or a small example. For machine-consumed output, use schema validation and retry logic in the application."},
  {problem:"The response invents facts or citations",fix:"Supply authoritative source material where possible, allow the model to report uncertainty, and independently verify factual claims. Do not treat confident language as evidence."},
  {problem:"The prompt has become enormous",fix:"Remove instructions that do not affect acceptance criteria. Move stable reference material to retrieval or application context when appropriate, and keep the core task concise."}
 ]}
><section><h2>A reusable prompt structure</h2><p>A durable prompt can usually be organized as: <strong>Goal → Context → Inputs → Constraints → Output format → Quality criteria → Uncertainty rule.</strong> Not every task needs every field, but this structure makes omissions easier to spot.</p></section><section><h2>Security note</h2><p>Prompts are not access-control systems. If an AI application can read private files, send messages, change records or execute commands, enforce permissions and approvals outside the prompt. Instructions can guide model behavior; they should not be the only barrier protecting consequential actions.</p></section></StepByStepGuide>}
