"use client";
import {useMemo,useState} from "react";
type Model={name:string,kind:string,privacy:number,cost:number,speed:number,reasoning:number,local:number,context:number,note:string};
const models:Model[]=[
{name:"Small local model",kind:"Local",privacy:5,cost:5,speed:4,reasoning:2,local:5,context:2,note:"Best when privacy, offline use and predictable infrastructure matter more than frontier capability."},
{name:"Large local model",kind:"Local",privacy:5,cost:3,speed:2,reasoning:4,local:5,context:3,note:"Higher local capability, but hardware requirements and operational complexity rise quickly."},
{name:"Fast cloud model",kind:"Cloud",privacy:2,cost:4,speed:5,reasoning:3,local:1,context:4,note:"A strong default for high-volume classification, extraction and interactive workloads."},
{name:"Frontier cloud model",kind:"Cloud",privacy:2,cost:2,speed:3,reasoning:5,local:1,context:5,note:"Best reserved for difficult tasks where higher capability creates measurable value."},
{name:"Hybrid routed stack",kind:"Hybrid",privacy:4,cost:4,speed:4,reasoning:5,local:4,context:4,note:"Route easy/private work locally or cheaply and escalate difficult tasks to stronger models."}
];
const labels:{[k:string]:string}={reasoning:"Reasoning quality",speed:"Speed",cost:"Cost efficiency",privacy:"Privacy/control",local:"Local deployment",context:"Long-context work"};
export default function ModelComparisonExplorer(){const [priority,setPriority]=useState("reasoning"),[deployment,setDeployment]=useState("any"); const ranked=useMemo(()=>models.filter(m=>deployment==="any"||m.kind.toLowerCase()===deployment).map(m=>({m,score:m[priority as keyof Model] as number})).sort((a,b)=>b.score-a.score),[priority,deployment]); return <div className="finder-shell"><div className="finder-controls"><label>What matters most?<select value={priority} onChange={e=>setPriority(e.target.value)}>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Deployment preference<select value={deployment} onChange={e=>setDeployment(e.target.value)}><option value="any">Any / show all</option><option value="local">Local only</option><option value="cloud">Cloud only</option><option value="hybrid">Hybrid</option></select></label><div><span className="finder-label">How to read this</span><p className="meta">These are architecture classes, not live vendor benchmarks. Scores illustrate trade-offs and help you decide what to benchmark with real models for your workload.</p></div></div><div className="finder-results" aria-live="polite"><div className="eyebrow">Comparison view · {labels[priority]}</div><h2>Compare by workload fit, not one leaderboard.</h2>{ranked.map(({m},i)=><article className="finder-result" key={m.name}><span>{String(i+1).padStart(2,"0")}</span><div><small>{m.kind}</small><h3>{m.name}</h3><p>{m.note}</p><div className="score-row">{Object.entries(labels).map(([k,v])=><span key={k} title={v}><b>{v}</b> {m[k as keyof Model]}/5</span>)}</div></div></article>)}</div></div>}
